### ISSUE TITLE
Font sizes in exported SVGs are wrong.

### ISSUE THREAD

**Issue by NiklasRentzCAU** [kieler/KLighD#10]
Exporting SVGs with the extended freehep exporter yields in wrong font sizes. This is especially bad for multiline text.

**Comment by NiklasRentzCAU** [comment]
This issue is migrated from the old KIELER Pragmatics JIRA issue tracker. See the old discussion on this ticket in [KIPRA-1534](https://rtsys.informatik.uni-kiel.de/jira/projects/KIPRA/issues/KIPRA-1534).

**Comment by soerendomroes** [comment]
I solved this issue for me by setting the font to "Helvetica" instead.

**Comment by NiklasRentzCAU** [comment]
Fixed with #52.
