### ISSUE TITLE
Positioing of Edge Label Decorators is Off

### ISSUE THREAD

**Issue by a-sr** [kieler/KLighD#116]
<img src="https://user-images.githubusercontent.com/25612037/169688575-05a47d16-76f6-4f94-816b-3e458b08f2f2.png" width="200">

The edge label decorator added by [DirectionalArrowsDecorator](https://github.com/kieler/KLighD/blob/013d6687ead7fee7041eff36f98e02375e5b2b56/plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/labels/decoration/DirectionalArrowsDecorator.java) is off by a few pixels.
However, this is only the case for up/down layout, in left/right the positions is correct.

![Screenshot from 2022-05-22 11-24-29](https://user-images.githubusercontent.com/25612037/169688837-fb271216-3d24-459f-8fff-b6fd4103fad3.png)

![Screenshot from 2022-05-22 11-24-35](https://user-images.githubusercontent.com/25612037/169688840-15fde188-aa72-4abf-acf9-1e789c7d2ab9.png)

Furthermore, the code to position the arrow looks correct in all cases (up/down, as well as left/right).
I tested a workaround: `setPlacement(arrow, left(2, 0), bottom(0, 0), right(0, 0), bottom(-4, 0));` for the [down positioning](https://github.com/kieler/KLighD/blob/013d6687ead7fee7041eff36f98e02375e5b2b56/plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/labels/decoration/DirectionalArrowsDecorator.java#L193) and it fixed the problem.
Yet, configuring an offset is semantically unjustified and the fact that this only occurs in up/down direction layout indicates a more fundamental problem elsewhere.

**Comment by NiklasRentzCAU** [comment]
This links back to an issue in ELK. As this is very minor, I don't think we would need to implement a workaround here until it is fixed in ELK.

**Comment by a-sr** [comment]
Ok
