### ISSUE TITLE
Remove batik

### ISSUE THREAD

**Issue by soerendomroes** [kieler/KLighD#134]
`de.cau.cs.kieler.klighd.piccolo.batik` does not seem to be used anymore and produces an error since `org.w3c.dom` is found twice.
What speaks against removing/archiving it? @NiklasRentzCAU @sailingKieler

**Comment by NiklasRentzCAU** [comment]
For reference: This error occurs in Eclipse when using Java11+.
As I do not wish to maintain some unused bundle I could just archive

**Comment by sailingKieler** [comment]
AFAIR batik was used to export PDFs, but I'm not aware of the quality of the output.
I'm fine with dropping it.
