### ISSUE TITLE
what's the best practice to hide or show children when click on the node

### ISSUE THREAD

**Issue by zeyupan888** [kieler/KLighD#177]
Hello,

I come here from another [elkjs thread](https://github.com/kieler/elkjs/issues/249) 
suggesting that KLighD has done something to auto-adjust the position based on visibility of node's children. 
Would you please give some advice? Thanks.

**Comment by NiklasRentzCAU** [comment]
When using KLighD, the API allows to store multiple representations of nodes in its KGraph/KRendering structure, i.e. a collapsed and expanded rendering. The expanded rendering usually contains a description to include the children within the node, while the collapsed rendering does not include that and therefore ignores rendering any of its children. Based on the view configuration, either the collapsed or the expanded version of the KGraph is then handed over to ELK for it to be layouted. That is, the elements are removed/added to/from the ELK graph representation and a new layout is computed based on this new graph structure.
So when using KLighD its view capabilities allow for such adjustments, when using plain ELK/elkjs the graph elements to be hidden have to be removed, as you suggested in the other thread.
