### ISSUE TITLE
The dashPattern of KLineStyle is set to unique values, but should not

### ISSUE THREAD

**Issue by NiklasRentzCAU** [kieler/KLighD#18]
The ECore model of KRendering defines that every element in the dashPattern List of KLineStyle needs to be unique. That causes custom patterns like '3 1 1 1' to not work as expected (it should create a dash-dot pattern with small spaces inbetween), and just show a '3 1' pattern in every resulting KGraph (it creates just a dash pattern with small spaces inbetween).

The attached image shows the bug: the left is how it is supposed to look (created here with the predefined dash-dot) and the right is how it is rendered currently.

[linePatternBug.png](https://rtsys.informatik.uni-kiel.de/jira/secure/attachment/14100/linePatternBug.png)

**Comment by NiklasRentzCAU** [comment]
This issue is migrated from the old KIELER Pragmatics JIRA issue tracker. See the old discussion on this ticket in [KIPRA-1922](https://rtsys.informatik.uni-kiel.de/jira/projects/KIPRA/issues/KIPRA-1922).

**Comment by sailingKieler** [comment]
I think there's a misunderstanding here.
If I recall right, in the dash pattern you specify the lengths between toggling between _drawing_ and _not drawing_, at least according to the SWT semantics of the dash pattern interpretation. If you for example add an additional `1` to your pattern, you should get a very different result.

**Comment by le-cds** [comment]
> If I recall right, in the dash pattern you specify the lengths between toggling between drawing and not drawing, at least according to the SWT semantics of the dash pattern interpretation.

According to this interpretation, the "3 1 1 1" pattern should recreate the dash-dot pattern, if I'm not mistaken:

![Untitled2](https://user-images.githubusercontent.com/7465584/84901837-4d8a6380-b0ac-11ea-9ec0-29d08dff7943.png)

If the problem is that a pattern cannot contain any number twice, then I would certainly think that's a bug.

**Comment by sailingKieler** [comment]
Maybe the attached diagram confused me, as the leftward edge looks like my expectation of the first edges drawing.

I remember that I spend quite some time on this while developing and documenting it for my thesis, but it could be that there's some issue in the mean time.

**Comment by sailingKieler** [comment]
A break point at https://github.com/kieler/KLighD/blob/120f3ceeb666180a5c4bc1ca6992553cd7b9f959/plugins/de.cau.cs.kieler.klighd.piccolo/src/de/cau/cs/kieler/klighd/piccolo/internal/controller/PNodeController.java#L461-L462 should clarify this.

**Comment by NiklasRentzCAU** [comment]
At that breakpoint the pattern is [3,1] instead of [3,1,1,1], so the model itself has a small bug.
I just replicated the issue and found the mistake: The dashPattern for the LineStyle in the ECore model has a 'unique' flag set to true, whereas it should be false.
Now that I know how to work with these ECore models, I will just create a quick PR to fix this.
