### ISSUE TITLE
is the de.cau.cs.kieler.klighd.standalone plugin still relevant?

### ISSUE THREAD

**Issue by HannesWell** [kieler/KLighD#213]
It looks like `de.cau.cs.kieler.klighd.standalone` is just an empty hull with a little bit of metadata, since it's only content was moved into the `de.cau.cs.kieler.klighd.setup plugin` via https://github.com/kieler/KLighD/pull/190.

Can it therefore be removed entirely or are there still use-cases for it?

**Comment by NiklasRentzCAU** [comment]
standalone is still relevant: its pom.xml lists dependencies to exporters, making the standalone the sole module necessary for a true standalone usable KLighD product. The setup module is now used for example for the language server, which also needs the non-Eclipse setup stuff, but not the exporters.
