### ISSUE TITLE
Add 'textLength' attribute to <svg:tspan> elements in SVG export

### ISSUE THREAD

**Issue by sailingKieler** [kieler/KLighD#44]
SVG exports of diagrams suffer (and will always suffer) from the different text renderings on different machines, and worse, even in different browsers on the same machine.

I just figured out that the SVG elements `<text>` and `<tspan>` offer the attributes `textLength` and `lengthAdjust`, which I wasn't aware of. See also https://codepen.io/tigt/post/more-robust-svg-text-with-lengthadjust-and-font-size-adjust

Hence, it would be valuable to add the designated `textLength` value to the generated SVG output and check whether that improves the portability of SVG exports.

**Comment by NiklasRentzCAU** [comment]
I also already had this problem when implementing the rendering of KText elements for the Sprotty-based viewer of KLighD. For that platform, I implemented the SVG rendering with that attribute [here](https://git.rtsys.informatik.uni-kiel.de/projects/KIELER/repos/keith/browse/keith-sprotty/src/views-rendering.tsx#516-546) as well, however, I found out that also may cause a slightly inconsistent look between glyphs in different texts on other platforms not natively supporting the font. A solution for optimal consistency would be to only use open and free-to-use fonts and include them in the viewer and the SVGs directly.

If you find another solution that preserves the texts in the SVG (not rasterizing them or converting them to paths), please let me know.

**Comment by sailingKieler** [comment]
> I found out that also may cause a slightly inconsistent look between glyphs in different texts on other platforms not natively supporting the font

That's for sure, but we're hopefully getting closer...

> If you find another solution that preserves the texts in the SVG (not rasterizing them or converting them to paths), please let me know.

Ok, but I guess that will never happen :-/

**Comment by sailingKieler** [comment]
I did some experiments with the generation of the `textLength` attribute for `<tspan>` elements.
Sadly Chromium messes up the rendering for multi `<tspan>` texts, at least for me in version 83.0.4103.116 on OSX:

<img width="978" alt="Bildschirmfoto 2020-07-13 um 15 18 17" src="https://user-images.githubusercontent.com/8513883/87309363-c7333700-c51c-11ea-869e-d9b53c25b02e.png">

more precisely only the last `<tspan>` element in the row seems to apply the `textLength` property properly.
(here with font `Monaco` (OSX, monospace), the first one is added without the `textLength` property as reference)

This seems to be documented here: https://bugs.chromium.org/p/chromium/issues/detail?id=375258

Consequence: I'm thinking about dropping the `<tspan>` approach and generating a group of `<text>` elements

**Comment by sailingKieler** [comment]
Btw. Firefox seem to not handle `textLength` for nested `<tspan>`s at all.

**Comment by NiklasRentzCAU** [comment]
This is exactly why I also opted to only use `<text>` and no `<tspan>`s in the Sprotty implementation. Again, I suggest looking at my implementation linked above, as it handles exactly this problem as well.

**Comment by sailingKieler** [comment]
> Again, I suggest looking at my implementation linked above, as it handles exactly this problem as well.

Unfortunately, that's only partly helpful. On the one hand I'm not trained in reading tsx, and the freeHEP SVG builder has its own sophistications on the other hand. Thanks anyway ;-)

**Comment by sailingKieler** [comment]
With the changes listed above the generated SVG is

<img width="801" alt="Bildschirmfoto 2020-07-16 um 12 22 37" src="https://user-images.githubusercontent.com/8513883/87661973-d2c36f80-c761-11ea-81c7-130f8a63e7de.png">

**Comment by sailingKieler** [comment]
@NiklasRentzCAU, @soerendomroes we can close this, right?

**Comment by NiklasRentzCAU** [comment]
Yes, the PR for this issue is merged into master and we did not notics any further problems regarding this issue.
Closing now.
