### ISSUE TITLE
Batik PDF Export calculates wrong X Coordinates for Text

### ISSUE THREAD

**Issue by a-sr** [kieler/KLighD#47]
When using the Batik PDF export, all KTexts are out of place. All x coordinates seem to have a wrong offset.
[Original](https://user-images.githubusercontent.com/25612037/86256346-83553f00-bbb8-11ea-8757-8424d26c8fd4.png) -> [Exported](https://github.com/kieler/KLighD/files/4858473/batik-pdf-export.pdf)

**Comment by uruuru** [comment]
It's been a while ... but I think it was hard or impossible to properly alter the behavior of the batik exporter. That's why we usually preferred freehep.

**Comment by sailingKieler** [comment]
I tend to close this as won't fix, as nobody is willing to spend the effort of investigating this, as it will always be a compromise...

**Comment by NiklasRentzCAU** [comment]
Sure, we wanted to drop the support for Batik anyways because we have the other exporter and this seems to not work currently, Closing as won't fix.
