### ISSUE TITLE
Incremental Update takes two Runs to fully update a modified Diagram

### ISSUE THREAD

**Issue by a-sr** [kieler/KLighD#48]
If a diagram is modified on-the-fly in the view (e.g. nodes are removed by an action) the incremental update requires two runs until changes in the model (new synthesis run) are correctly applied to the diagram. The first result is always broken.

### Example

1. Fresh diagram.
![cycle_filter1](https://user-images.githubusercontent.com/25612037/86257395-c19f2e00-bbb9-11ea-99cc-c3c15c9e3f1f.png)
2. The user pressed "Filter Cycle" to remove all nodes that are not highlighted. Changes were made by an action (no synthesis run).
![cycle_filter2](https://user-images.githubusercontent.com/25612037/86257499-e98e9180-bbb9-11ea-91b7-f7bec54c499a.png)
3. The user fixed the problem and saved the model. A new synthesis was invoked but the result is broken.
![cycle_filter3](https://user-images.githubusercontent.com/25612037/86257627-180c6c80-bbba-11ea-95b7-f73f56d8521c.png)
4. Only after another update (synthesis re-run) the resulting diagram is correctly displayed.
![cycle_filter4](https://user-images.githubusercontent.com/25612037/86257684-2fe3f080-bbba-11ea-8334-22711f7c52e0.png)

**Comment by NiklasRentzCAU** [comment]
Fixed in [d21bf90](https://github.com/kieler/KLighD/commit/d21bf90432c4fecb9cf2899c93c64e00da86dc3a).
