### ISSUE TITLE
Register actions via service loader

### ISSUE THREAD

**Issue by soerendomroes** [kieler/KLighD#50]
Currently only syntheses are registered via service loader and in a `plugin.xml`.
To successfully use KLighD in a non Eclipse context one should also register the actions and not only the syntheses via a service loader.

**Comment by NiklasRentzCAU** [comment]
Fixed with [307c8f](https://github.com/kieler/KLighD/commit/307c8f6ea48d20d3ddde0eb0205c01df60bb5415)
