### ISSUE TITLE
Drop dead code

### ISSUE THREAD

**Issue by sailingKieler** [kieler/KLighD#54]
https://github.com/kieler/KLighD/blob/d21bf90432c4fecb9cf2899c93c64e00da86dc3a/plugins/de.cau.cs.kieler.klighd.piccolo/src/de/cau/cs/kieler/klighd/piccolo/internal/controller/KLabelRenderingController.java#L96-L102

@a-sr @NiklasRentzCAU I would like to remove this code, as `getGraphElement().getProperties().contains(KlighdProperties.NOT_SELECTABLE)` will never be satisfied. `getProperties()` returns an `EMap<IProperty<?>, Object>` containing `IPropertyToObjectMapImpl`s. Hence, `KlighdProperties.NOT_SELECTABLE` will never be "contained".

Also from a conceptual point of view I don't like these kind of built-in magics.
If I remember right, back then I decided leave the freedom of fine-grained control on the selectability of labels and text fields to the diagram synthesis developers on purpose.

Any objections?

**Comment by NiklasRentzCAU** [comment]
I only ever used the suppression of the selectability on KTexts and other rendering elements, not on graph element such as labels. As far as I can see this is also never used for labels anywhere in our code, so this could just be removed safely.

**Comment by a-sr** [comment]
I think the idea was that you usually don't need to create a KText for a label and this way you can configure the selectability of the automatically created KText via the label. However, if it does not work, then we probably don't use it, hence you can delete it.

**Comment by sailingKieler** [comment]
> that you usually don't need to create a KText for a label and this way you can configure the selectability of the automatically created KText via the label

Sure. However, I would expect this kind of thing in some convenience API like the KLabelExtensions, not in the runtime.

I'll take care about it together with #43.
