### ISSUE TITLE
Getter of delegate in ReinitializingDiagramSynthesisProxy may return null

### ISSUE THREAD

**Issue by NiklasRentzCAU** [kieler/KLighD#61]
When calling the public [getDelegate()](https://github.com/kieler/KLighD/blob/cac077b87e38ce308a2472ec2ad585c5453dc38b/plugins/de.cau.cs.kieler.klighd/src/de/cau/cs/kieler/klighd/syntheses/ReinitializingDiagramSynthesisProxy.java#L235) funciton of the ReinitializingDiagramSynthesisProxy, this returns null if the delegate has never been initialized before by calling some other function of that class first. I suggest this method also gets this existence check when getting the delegate as most other functions have as well:
```
if (this.transformationDelegate == null) {
    this.transformationDelegate = getNewDelegateInstance();
}
```
@sailingKieler Was there any reason why this is not checked when getting the delegate directly? I currently have a use case [here](https://github.com/kieler/KLighD/blob/b58a9b6b84a5d16594f70457ec8eae54340f43cb/plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/klighd/lsp/KGraphLanguageServerExtension.xtend#L171) where I sometimes get a NPE because of this, which could be fixed there by just putting a toString() and not using it, just so that the delegate is initialized. That solution however is a quite hacky way that does not seem intended. I'll create a PR to solve this if you think this does no other harm.

**Comment by sailingKieler** [comment]
> Was there any reason why this is not checked when getting the delegate directly

I don't remember anymore. Maybe to let the getter cause no side effect.
Cannot see any usage of this method except for some addition by @a-sr in 1c5b46a
Basically, I don't mind. 

May I ask, why you bother with the class name instead of the ID? Should be equal or similar in the common case.

**Comment by NiklasRentzCAU** [comment]
That's because I don't want to rely on the ID being built the way they are most commonly so I can just take the class name as the easiest human-readable form of the ID. That way I don't have to rely on taking the last section after splitting the ID on its '.'.
![SynthesisChooser](https://user-images.githubusercontent.com/47597619/88931146-c0c2f000-d27c-11ea-8f83-4630b59b574a.png)
