### ISSUE TITLE
Rename classes for layered and rectpack interactive

### ISSUE THREAD

**Issue by NiklasRentzCAU** [kieler/KLighD#67]
The classes for interactive functionality for the layered and rectpacking algorithms have confusing names (ConstraintsLanguageServerExtension for the layered class, RectPackInterativeLanguageServerExtension for the rectpacking class). Futhermore, they both have 'LanguageServerExtension' in their names and implement ILanguageServerExtension, although they do not provide any functionality to the LSP directly, but rather extend the DiagramServer used.
I would suggest removing the interface implementations and renaming the classes to 'RectPackInteractiveExtension' and 'LayeredInteractiveExtension', respectively, or something also involving 'DiagramExtension' or 'DiagramServerExtensoin'.

**Comment by soerendomroes** [comment]
I will rename them both, but they are language server extensions, since they use the `LanguageClient` to change a file. I will therefore rename them to `LayeredInteractiveLanguageServerExtension` and `RectpackingILSE`
