### ISSUE TITLE
Update Behavior Question

### ISSUE THREAD

**Issue by parnold-x** [kieler/KLighD#68]
Hi, 
I am not sure if this is a ELK issue or fits here.
I am visualize a xtext model. I reflect xtext changes on the klighd model. Now when I do a change which will just change the color of a node, I would prefer that no movement happens and just the color changes. This works sometimes but sometimes not somehow randomly. See attached video.  I thought first this can be tweaked in ELK, so I set interactive to true and consider model order in the layered algorithm but this seems to do nothing.
Can I tweak something to make this happen?

[Video](https://www.dropbox.com/s/7abn3qfdnjyvuzx/klighd%20-%20color%20change.mp4?dl=0)

**Comment by NiklasRentzCAU** [comment]
This is an issue in the incremental update strategy and seems to be related to #1 which is fixed in the current master. Could you retry this with the current nightly build if the issue persists there?

**Comment by parnold-x** [comment]
I am using the most recent master and still see the behavior. When I find time I will try to debug it. Thank you for your answer.

**Comment by soerendomroes** [comment]
@parnold-x A little off topic, but have you opened an issue in ELK regarding the problems with the interactive option and the consider model order option?

**Comment by parnold-x** [comment]
@soerendomroes Nope, I was what's the cause of the issue I see.

**Comment by soerendomroes** [comment]
@parnold-x If you are unsure whether this might be an ELK problem or how the ELK options work please open a question issue in ELK and I will try to help you.

**Comment by parnold-x** [comment]
Ok, I finally came back to this and debugged it. This was not a issue in KLighD or ELK instead it was a problem in my Synthesis.
Thanks again
