### ISSUE TITLE
Enable customization of ToolTip in diagram browser

### ISSUE THREAD

**Issue by sailingKieler** [kieler/KLighD#73]
The tooltip implementation is currently hard-coded in [PiccoloViewer](https://github.com/kieler/KLighD/blob/8d78c50f883ca5934f7c2862a6107c6bbb6e0bb3/plugins/de.cau.cs.kieler.klighd.piccolo/src/de/cau/cs/kieler/klighd/piccolo/viewer/PiccoloViewer.java#L131-L147).

A client raised the question for enabling some customization instead of this hard-wiring.

**Comment by sailingKieler** [comment]
> Edit: Just noticed, the commits for fixing this are not yet on the master branch, I guess we would need that first to close this.

Seems to be the case. I don't have an overview over the various branches anymore.
@NiklasRentzCAU feel free to cherry pick the relevant change and push it to master.

**Comment by NiklasRentzCAU** [comment]
Cherry-picked to master, closing this.
