### ISSUE TITLE
Build: broken due to missing javax.annotations-api:1.3.5

### ISSUE THREAD

**Issue by NiklasRentzCAU** [kieler/KLighD#82]
The issue originates from some Eclipse Releases not being available on Maven Central, see here: https://github.com/eclipse/elk/issues/752
As this also affects the previous ELK 0.7.0 release, we might have to enable a temporary fix as ELK does to get the build working again.

**Comment by uruuru** [comment]
See eclipse/elk#752 for a workaround and a corresponding bugzilla issue.
