### ISSUE TITLE
Kerning sometimes wrong

### ISSUE THREAD

**Issue by spirritus** [kieler/KLighD#84]
Hi there,

when zooming in and out the kerning betwee letters is calculated.
However, sometime the result is wrong. See picture.
![KerningError](https://user-images.githubusercontent.com/1154316/120202568-0480e000-c227-11eb-831c-6990dc84c41f.png)

**Comment by sailingKieler** [comment]
That's an issue of SWT/the underlying window system in combination with the chosen or default font,
KLighD can't do anything here.

Closing as invalid.
